head -"${arg1}" "${sourceFile}"
head -"${arg1}" < "${sourceFile}"
head -n "${arg1}" "${sourceFile}"
head -n "${arg1}" < "${sourceFile}"
head -n"${arg1}" "${sourceFile}"
head -n"${arg1}" < "${sourceFile}"
head -n +"${arg1}" "${sourceFile}"
head -n +"${arg1}" < "${sourceFile}"
head -n+"${arg1}" "${sourceFile}"
head -n+"${arg1}" < "${sourceFile}"
sed -n "1,${arg1}p" "${sourceFile}"
sed -n "1,${arg1}p" < "${sourceFile}"
sed "${arg1}"'q' "${sourceFile}"
sed "${arg1}"'q' < "${sourceFile}"
sed '1,'"${arg1}"'!d' "${sourceFile}"
sed '1,'"${arg1}"'!d' < "${sourceFile}"
awk 'NR > '"${arg1}"' { exit } { print $0 }' "${sourceFile}"
awk 'NR > '"${arg1}"' { exit } { print $0 }' < "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${arg1}"' ) exit }' "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${arg1}"' ) exit }' < "${sourceFile}"
awk '{ if( NR > '"${arg1}"' ) exit ; print $0 }' "${sourceFile}"
awk '{ if( NR > '"${arg1}"' ) exit ; print $0 }' < "${sourceFile}"
awk '{ if( NR > '"${arg1}"' ) { exit } print $0 }' "${sourceFile}"
awk '{ if( NR > '"${arg1}"' ) { exit } print $0 }' < "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${arg1}"' ) exit }' "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${arg1}"' ) exit }' < "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${arg1}"' ) { exit }  }' "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${arg1}"' ) { exit } }' < "${sourceFile}"
awk 'NR >= '"${arg1}"' { print $0 ; exit } { print $0 }' "${sourceFile}"
awk 'NR >= '"${arg1}"' { print $0 ; exit } { print $0 }' < "${sourceFile}"
awk 'NR <= '"${arg1}"' { print $0 }' "${sourceFile}"
awk 'NR <= '"${arg1}"' { print $0 }' < "${sourceFile}"
awk '{ if( NR <= '"${arg1}"' ) print $0 }' "${sourceFile}"
awk '{ if( NR <= '"${arg1}"' ) print $0 }' < "${sourceFile}"
perl -ne '1..'"${arg1}"' and print' "${sourceFile}"
perl -ne '1..'"${arg1}"' and print' < "${sourceFile}"
