tr -s "'${arg1}'" < "${sourceFile}"
tr --squeeze-repeats "'${arg1}'" < "${sourceFile}"
sed 's/'"${arg1}"''"${arg1}"'*/'"${arg1}"'/g' "${sourceFile}"
sed 's/'"${arg1}"''"${arg1}"'*/'"${arg1}"'/g' < "${sourceFile}"
sed -e 's/'"${arg1}"''"${arg1}"'*/'"${arg1}"'/g' "${sourceFile}"
sed -e 's/'"${arg1}"''"${arg1}"'*/'"${arg1}"'/g' < "${sourceFile}"
sed -e's/'"${arg1}"''"${arg1}"'*/'"${arg1}"'/g' "${sourceFile}"
sed -e's/'"${arg1}"''"${arg1}"'*/'"${arg1}"'/g' < "${sourceFile}"
sed -r 's/'"${arg1}"'+/'"${arg1}"'/g' "${sourceFile}"
sed -r 's/'"${arg1}"'+/'"${arg1}"'/g' < "${sourceFile}"
sed -r -e 's/'"${arg1}"'+/'"${arg1}"'/g' "${sourceFile}"
sed -r -e 's/'"${arg1}"'+/'"${arg1}"'/g' < "${sourceFile}"
sed -r -e's/'"${arg1}"'+/'"${arg1}"'/g' "${sourceFile}"
sed -r -e's/'"${arg1}"'+/'"${arg1}"'/g' < "${sourceFile}"
sed -re 's/'"${arg1}"'+/'"${arg1}"'/g' "${sourceFile}"
sed -re 's/'"${arg1}"'+/'"${arg1}"'/g' < "${sourceFile}"
sed -re's/'"${arg1}"'+/'"${arg1}"'/g' "${sourceFile}"
sed -re's/'"${arg1}"'+/'"${arg1}"'/g' < "${sourceFile}"
