cut -d ';' -f "${selectedField}" "${sourceFile}"
cut -d ';' -f "${selectedField}" < "${sourceFile}"
cut -d';' -f"${selectedField}" "${sourceFile}"
cut -d';' -f"${selectedField}" < "${sourceFile}"
awk -F ';' '{ print $'"${selectedField}"' }' "${sourceFile}"
awk -F ';' '{ print $'"${selectedField}"' }' < "${sourceFile}"
awk -F';' '{ print $'"${selectedField}"' }' "${sourceFile}"
awk -F';' '{ print $'"${selectedField}"' }' < "${sourceFile}"
awk  --field-separator ';' '{ print $'"${selectedField}"' }' "${sourceFile}"
awk  --field-separator ';' '{ print $'"${selectedField}"' }' < "${sourceFile}"
awk  'BEGIN{ FS=";" } { print $'"${selectedField}"' }' "${sourceFile}"
awk  'BEGIN{ FS=";" } { print $'"${selectedField}"' }' < "${sourceFile}"
