sed '/^[ 	]*#/d' "${sourceFile}"
sed '/^[ 	]*#/d' < "${sourceFile}"
grep -v '^[ 	]*#' "${sourceFile}"
grep -v '^[ 	]*#' < "${sourceFile}"
grep -v '^\\s*#' "${sourceFile}"
grep -v '^\\s*#' < "${sourceFile}"
egrep -v '^[ 	]*#' "${sourceFile}"
egrep -v '^[ 	]*#' < "${sourceFile}"
egrep -v '^\\s*#' "${sourceFile}"
egrep -v '^\\s*#' < "${sourceFile}"
awk '$0 !~ /^[ 	]*#/ { print $0 }' "${sourceFile}"
awk '$0 !~ /^[ 	]*#/ { print $0 }' < "${sourceFile}"
awk '{ if ( $0 !~ "^[ 	]*#" ) { print $0 } }' "${sourceFile}"
awk '{ if ( $0 !~ "^[ 	]*#" ) { print $0 } }' < "${sourceFile}"
