sed '/^[ 	]*#/d' "${sourceFile}"
sed '/^[ 	]*#/d' < "${sourceFile}"
sed '/^[ \\t]*#/d' "${sourceFile}"
sed '/^[ \\t]*#/d' < "${sourceFile}"
sed '/^\\s*#/d' "${sourceFile}"
sed '/^\\s*#/d' < "${sourceFile}"
sed '/^[[:space:]]*#/d' "${sourceFile}"
sed '/^[[:space:]]*#/d' < "${sourceFile}"
sed '/^[[:blank:]]*#/d' "${sourceFile}"
sed '/^[[:blank:]]*#/d' < "${sourceFile}"
sed -n '/^[ 	]*#/!p' "${sourceFile}"
sed -n '/^[ 	]*#/!p' < "${sourceFile}"
sed -n '/^[ \\t]*#/!p' "${sourceFile}"
sed -n '/^[ \\t]*#/!p' < "${sourceFile}"
sed -n '/^\\s*#/!p' "${sourceFile}"
sed -n '/^\\s*#/!p' < "${sourceFile}"
sed -n '/^[[:space:]]*#/!p' "${sourceFile}"
sed -n '/^[[:space:]]*#/!p' < "${sourceFile}"
sed -n '/^[[:blank:]]*#/!p' "${sourceFile}"
sed -n '/^[[:blank:]]*#/!p' < "${sourceFile}"
grep -v '^[ 	]*#' "${sourceFile}"
grep -v '^[ 	]*#' < "${sourceFile}"
grep -v -P '^[ \\t]*#' "${sourceFile}"
grep -v -P '^[ \\t]*#' < "${sourceFile}"
grep -vP '^[ \\t]*#' "${sourceFile}"
grep -vP '^[ \\t]*#' < "${sourceFile}"
grep -v '^\\s*#' "${sourceFile}"
grep -v '^\\s*#' < "${sourceFile}"
grep -v '^[[:space:]]*#' "${sourceFile}"
grep -v '^[[:space:]]*#' < "${sourceFile}"
grep -v '^[[:blank:]]*#' "${sourceFile}"
grep -v '^[[:blank:]]*#' < "${sourceFile}"
egrep -v '^[ 	]*#' "${sourceFile}"
egrep -v '^[ 	]*#' < "${sourceFile}"
egrep -v '^\\s*#' "${sourceFile}"
egrep -v '^\\s*#' < "${sourceFile}"
egrep -v '^[[:space:]]*#' "${sourceFile}"
egrep -v '^[[:space:]]*#' < "${sourceFile}"
egrep -v '^[[:blank:]]*#' "${sourceFile}"
egrep -v '^[[:blank:]]*#' < "${sourceFile}"
awk '$0 !~ /^[ 	]*#/ { print $0 }' "${sourceFile}"
awk '$0 !~ /^[ 	]*#/ { print $0 }' < "${sourceFile}"
awk '{ if ( $0 !~ "^[ 	]*#" ) { print $0 } }' "${sourceFile}"
awk '{ if ( $0 !~ "^[ 	]*#" ) { print $0 } }' < "${sourceFile}"
