tail -n +"${arg1}" "${sourceFile}"
tail -n +"${arg1}" < "${sourceFile}"
tail -n+"${arg1}" "${sourceFile}"
tail -n+"${arg1}" < "${sourceFile}"
sed -n ''"${arg1}"',$p' "${sourceFile}"
sed -n ''"${arg1}"',$p' < "${sourceFile}"
sed ''"${arg1}"',$!d' "${sourceFile}"
sed ''"${arg1}"',$!d' < "${sourceFile}"
sed -n -e ''"${arg1}"',$p' "${sourceFile}"
sed -n -e ''"${arg1}"',$p' < "${sourceFile}"
sed -e ''"${arg1}"',$!d' "${sourceFile}"
sed -e ''"${arg1}"',$!d' < "${sourceFile}"
awk 'NR >= '"${arg1}"' { print $0 }' "${sourceFile}"
awk 'NR >= '"${arg1}"' { print $0 }' < "${sourceFile}"
awk '{  if ( NR >= '"${arg1}"' ) print $0 }' "${sourceFile}"
awk '{  if ( NR >= '"${arg1}"' ) print $0 }' < "${sourceFile}"
