sed -n -e "${arg1}p" -e "${arg2}p" "${sourceFile}"
sed -n -e "${arg1}p" -e "${arg2}p" < "${sourceFile}"
sed -n -e "${arg1}p;${arg2}p" "${sourceFile}"
sed -n -e "${arg1}p;${arg2}p" < "${sourceFile}"
sed -n "${arg1}p;${arg2}p" "${sourceFile}"
sed -n "${arg1}p;${arg2}p" < "${sourceFile}"
sed -n -e "${arg1}p" -e "${arg2}p" -e "${arg2}q" "${sourceFile}"
sed -n -e "${arg1}p" -e "${arg2}p" -e "${arg2}q" < "${sourceFile}"
sed -n -e "${arg1}p;${arg2}p;${arg2}q" "${sourceFile}"
sed -n -e "${arg1}p;${arg2}p;${arg2}q" < "${sourceFile}"
sed -n "${arg1}p;${arg2}p;${arg2}q" "${sourceFile}"
sed -n "${arg1}p;${arg2}p;${arg2}q" < "${sourceFile}"
awk 'NR == '"${arg1}"' ; NR == '"${arg2}"'' "${sourceFile}"
awk 'NR == '"${arg1}"' ; NR == '"${arg2}"'' < "${sourceFile}"
awk 'NR == '"${arg1}"' ; NR == '"${arg2}"' { print $0 }' "${sourceFile}"
awk 'NR == '"${arg1}"' ; NR == '"${arg2}"' { print $0 }' < "${sourceFile}"
awk 'NR == '"${arg1}"' { print $0 } ; NR == '"${arg2}"' { print $0 }' "${sourceFile}"
awk 'NR == '"${arg1}"' { print $0 } ; NR == '"${arg2}"' { print $0 }' < "${sourceFile}"
awk 'NR == '"${arg1}"' ; NR == '"${arg2}"' { print $0 ; exit }' "${sourceFile}"
awk 'NR == '"${arg1}"' ; NR == '"${arg2}"' { print $0 ; exit }' < "${sourceFile}"
awk 'NR == '"${arg1}"' { print $0 } NR == '"${arg2}"' { print $0 }' "${sourceFile}"
awk 'NR == '"${arg1}"' { print $0 } NR == '"${arg2}"' { print $0 }' < "${sourceFile}"
awk 'NR == '"${arg1}"' { print $0 } NR == '"${arg2}"' { print $0 ; exit }' "${sourceFile}"
awk 'NR == '"${arg1}"' { print $0 } NR == '"${arg2}"' { print $0 ; exit }' < "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' ) print $0 ; if ( NR == '"${arg2}"' ) print $0 }' "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' ) print $0 ; if ( NR == '"${arg2}"' ) print $0 }' < "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' ) { print $0 } ; if ( NR == '"${arg2}"' ) { print $0 } }' "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' ) { print $0 } ; if ( NR == '"${arg2}"' ) { print $0 } }' < "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' ) { print $0 } ; if ( NR == '"${arg2}"' ) { print $0 ; exit } }' "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' ) { print $0 } ; if ( NR == '"${arg2}"' ) { print $0 ; exit } }' < "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) print $0 }' "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) print $0 }' < "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) { print $0 } }' "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) { print $0 } }' < "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) print $0 ; if ( NR == '"${arg2}"' ) exit }' "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) print $0 ; if ( NR == '"${arg2}"' ) exit }' < "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) { print $0 } ; if ( NR == '"${arg2}"' ) { exit } }' "${sourceFile}"
awk '{  if ( NR == '"${arg1}"' || NR == '"${arg2}"' ) { print $0 } ; if ( NR == '"${arg2}"' ) { exit } }' < "${sourceFile}"
