head -"${selectedLines}" "${sourceFile}"
head -"${selectedLines}" < "${sourceFile}"
head -n "${selectedLines}" "${sourceFile}"
head -n "${selectedLines}" < "${sourceFile}"
head -n"${selectedLines}" "${sourceFile}"
head -n"${selectedLines}" < "${sourceFile}"
head -n +"${selectedLines}" "${sourceFile}"
head -n +"${selectedLines}" < "${sourceFile}"
head -n+"${selectedLines}" "${sourceFile}"
head -n+"${selectedLines}" < "${sourceFile}"
sed -n "1,${selectedLines}p" "${sourceFile}"
sed -n "1,${selectedLines}p" < "${sourceFile}"
sed "${selectedLines}"'q' "${sourceFile}"
sed "${selectedLines}"'q' < "${sourceFile}"
sed '1,'"${selectedLines}"'!d' "${sourceFile}"
sed '1,'"${selectedLines}"'!d' < "${sourceFile}"
awk 'NR > '"${selectedLines}"' { exit } { print $0 }' "${sourceFile}"
awk 'NR > '"${selectedLines}"' { exit } { print $0 }' < "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${selectedLines}"' ) exit }' "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${selectedLines}"' ) exit }' < "${sourceFile}"
awk '{ if( NR > '"${selectedLines}"' ) exit ; print $0 }' "${sourceFile}"
awk '{ if( NR > '"${selectedLines}"' ) exit ; print $0 }' < "${sourceFile}"
awk '{ if( NR > '"${selectedLines}"' ) { exit } print $0 }' "${sourceFile}"
awk '{ if( NR > '"${selectedLines}"' ) { exit } print $0 }' < "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${selectedLines}"' ) exit }' "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${selectedLines}"' ) exit }' < "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${selectedLines}"' ) { exit }  }' "${sourceFile}"
awk '{ print $0 ; if( NR >= '"${selectedLines}"' ) { exit } }' < "${sourceFile}"
awk 'NR >= '"${selectedLines}"' { print $0 ; exit } { print $0 }' "${sourceFile}"
awk 'NR >= '"${selectedLines}"' { print $0 ; exit } { print $0 }' < "${sourceFile}"
awk 'NR <= '"${selectedLines}"' { print $0 }' "${sourceFile}"
awk 'NR <= '"${selectedLines}"' { print $0 }' < "${sourceFile}"
awk '{ if( NR <= '"${selectedLines}"' ) print $0 }' "${sourceFile}"
awk '{ if( NR <= '"${selectedLines}"' ) print $0 }' < "${sourceFile}"
perl -ne '1..'"${selectedLines}"' and print' "${sourceFile}"
perl -ne '1..'"${selectedLines}"' and print' < "${sourceFile}"
