tail -"${arg1}" "${sourceFile}"
tail -"${arg1}" < "${sourceFile}"
tail -n "${arg1}" "${sourceFile}"
tail -n "${arg1}" < "${sourceFile}"
tail -n"${arg1}" "${sourceFile}"
tail -n"${arg1}" < "${sourceFile}"
